-- ================================================================
-- SCHEMA: Normalização Semântica com Qdrant + E5 + NER
-- Database: falai
-- Description: Estrutura completa para geração de embeddings e sintomas
-- ================================================================

BEGIN;

-- ================================================================
-- CRIAR SCHEMA
-- ================================================================

CREATE SCHEMA IF NOT EXISTS falai_doutor_normalizacao;


-- ================================================================
-- EXTENSÕES (opcional)
-- ================================================================

-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- ================================================================
-- TABELA: CATEGORIAS DE SINTOMAS
-- ================================================================

CREATE TABLE IF NOT EXISTS falai_doutor_normalizacao.categorias_sintomas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT NOT NULL UNIQUE,
    nome TEXT NOT NULL,
    descricao TEXT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ================================================================
-- TABELA: SINTOMAS (conceitos canônicos)
-- ================================================================
-- Termos médicos canônicos/normalizados que serão indexados no Qdrant

CREATE TABLE IF NOT EXISTS falai_doutor_normalizacao.sintomas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    termo TEXT NOT NULL UNIQUE,
    termo_busca TEXT GENERATED ALWAYS AS (LOWER(TRIM(termo))) STORED,
    categoria_id BIGINT REFERENCES falai_doutor_normalizacao.categorias_sintomas(id) ON DELETE RESTRICT,
    descricao TEXT,                       -- descrição adicional
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    versao INTEGER NOT NULL DEFAULT 1 CHECK (versao >= 1),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (termo_busca)
);

CREATE INDEX IF NOT EXISTS idx_sintomas_termo ON falai_doutor_normalizacao.sintomas(termo);
CREATE INDEX IF NOT EXISTS idx_sintomas_categoria_id ON falai_doutor_normalizacao.sintomas(categoria_id);
CREATE INDEX IF NOT EXISTS idx_sintomas_ativo ON falai_doutor_normalizacao.sintomas(ativo);


-- ================================================================
-- TABELA: SINONIMOS (linguagem do usuário)
-- ================================================================
-- Variações de termos que o usuário pode usar; apontam para sintomas canônicos

CREATE TABLE IF NOT EXISTS falai_doutor_normalizacao.sinonimos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sintoma_id BIGINT NOT NULL REFERENCES falai_doutor_normalizacao.sintomas(id) ON DELETE CASCADE,
    termo TEXT NOT NULL,                  -- ex: "aperto no coração"
    termo_busca TEXT GENERATED ALWAYS AS (LOWER(TRIM(termo))) STORED,
    origem TEXT NOT NULL CHECK (origem IN ('manual', 'llm', 'ollama', 'usuario', 'admin', 'importacao', 'candidato_aprovado')),
    status TEXT NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'aprovado', 'rejeitado', 'inativo')),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_sinonimos_termo_sintoma_id
    ON falai_doutor_normalizacao.sinonimos(termo_busca, sintoma_id);
CREATE INDEX IF NOT EXISTS idx_sinonimos_termo ON falai_doutor_normalizacao.sinonimos(termo);
CREATE INDEX IF NOT EXISTS idx_sinonimos_sintoma_id ON falai_doutor_normalizacao.sinonimos(sintoma_id);
CREATE INDEX IF NOT EXISTS idx_sinonimos_status ON falai_doutor_normalizacao.sinonimos(status);


-- ================================================================
-- TABELA: CID-10
-- ================================================================
-- Classificação Internacional de Doenças (CID-10)

CREATE TABLE IF NOT EXISTS falai_doutor_normalizacao.cid10 (
    codigo TEXT PRIMARY KEY,              -- ex: "R07" (dor torácica)
    descricao TEXT NOT NULL,
    subcategorias TEXT,                   -- ex: "R07.1, R07.2, R07.9"
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_cid10_descricao ON falai_doutor_normalizacao.cid10(descricao);


-- ================================================================
-- TABELA: RELAÇÃO SINTOMA ↔ CID-10
-- ================================================================
-- Many-to-many: um sintoma pode mapear para múltiplos códigos CID-10

CREATE TABLE IF NOT EXISTS falai_doutor_normalizacao.sintoma_cid10 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sintoma_id BIGINT NOT NULL REFERENCES falai_doutor_normalizacao.sintomas(id) ON DELETE CASCADE,
    cid_codigo TEXT NOT NULL REFERENCES falai_doutor_normalizacao.cid10(codigo) ON DELETE RESTRICT,
    confianca REAL NOT NULL DEFAULT 1.0 CHECK (confianca BETWEEN 0 AND 1),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(sintoma_id, cid_codigo)
);

CREATE INDEX IF NOT EXISTS idx_sintoma_cid10_sintoma_id ON falai_doutor_normalizacao.sintoma_cid10(sintoma_id);
CREATE INDEX IF NOT EXISTS idx_sintoma_cid10_cid_codigo ON falai_doutor_normalizacao.sintoma_cid10(cid_codigo);


-- ================================================================
-- TABELA: INPUTS (logs do sistema)
-- ================================================================
-- Registro de todas as entradas/requisições processadas

CREATE TABLE IF NOT EXISTS falai_doutor_normalizacao.inputs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    texto_original TEXT NOT NULL,         -- texto bruto do usuário
    hash_input TEXT,                      -- SHA256 para deduplicação
    modelo TEXT DEFAULT 'qwen3',          -- modelo LLM usado
    versao_prompt TEXT,                   -- versão do prompt MTS
    versao_vocabulario TEXT,              -- versão do vocabulário de sintomas
    ip_origem TEXT,                       -- IP do cliente (se aplicável)
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_inputs_hash ON falai_doutor_normalizacao.inputs(hash_input);
CREATE INDEX IF NOT EXISTS idx_inputs_criado_em ON falai_doutor_normalizacao.inputs(criado_em);


-- ================================================================
-- TABELA: OUTPUTS (resultado da classificação)
-- ================================================================
-- Saída completa estruturada do classificador MTS

CREATE TABLE IF NOT EXISTS falai_doutor_normalizacao.outputs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    input_id BIGINT NOT NULL REFERENCES falai_doutor_normalizacao.inputs(id) ON DELETE CASCADE,
    json_resultado JSONB NOT NULL,        -- resposta TriageResponse completa
    classificacao TEXT NOT NULL CHECK (classificacao IN ('Vermelho', 'Laranja', 'Amarelo', 'Verde', 'Azul', 'Indeterminado')),
    tempo_processamento_ms INTEGER,       -- latência em ms
    confianca TEXT NOT NULL CHECK (confianca IN ('alta', 'media', 'baixa')),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_outputs_input_id ON falai_doutor_normalizacao.outputs(input_id);
CREATE INDEX IF NOT EXISTS idx_outputs_classificacao ON falai_doutor_normalizacao.outputs(classificacao);
CREATE INDEX IF NOT EXISTS idx_outputs_confianca ON falai_doutor_normalizacao.outputs(confianca);
CREATE INDEX IF NOT EXISTS idx_outputs_criado_em ON falai_doutor_normalizacao.outputs(criado_em);


-- ================================================================
-- TABELA: BASE_CANDIDATA (aprendizado)
-- ================================================================
-- Termos normalizados que aguardam auditoria e correlação com sintoma_id
-- Retroalimentação para melhorar o vocabulário
-- Nota: A correlação com sintoma_id será feita por um serviço posterior após aprovação

CREATE TABLE IF NOT EXISTS falai_doutor_normalizacao.base_candidata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    input_original TEXT NOT NULL,         -- termo original do usuário
    normalizado_sugerido TEXT NOT NULL,   -- sintoma normalizado (sem apontar para tabela)
    score_e5 REAL CHECK (score_e5 IS NULL OR score_e5 BETWEEN 0 AND 1),
    score_ollama_confianca TEXT CHECK (score_ollama_confianca IS NULL OR score_ollama_confianca IN ('alta', 'media', 'baixa')),
    origem TEXT NOT NULL DEFAULT 'llm' CHECK (origem IN ('llm', 'ollama', 'usuario', 'admin')),
    status TEXT NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'aprovado', 'rejeitado')),
    revisado BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_base_candidata_status ON falai_doutor_normalizacao.base_candidata(status);
CREATE INDEX IF NOT EXISTS idx_base_candidata_normalizado_sugerido ON falai_doutor_normalizacao.base_candidata(normalizado_sugerido);
CREATE INDEX IF NOT EXISTS idx_base_candidata_criado_em ON falai_doutor_normalizacao.base_candidata(criado_em);
CREATE INDEX IF NOT EXISTS idx_base_candidata_score_e5 ON falai_doutor_normalizacao.base_candidata(score_e5);


-- ================================================================
-- TABELA: AUDITORIA (rastreamento de decisões)
-- ================================================================
-- Registro de aprovações, rejeições e correções

CREATE TABLE IF NOT EXISTS falai_doutor_normalizacao.auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidato_id BIGINT NOT NULL REFERENCES falai_doutor_normalizacao.base_candidata(id) ON DELETE CASCADE,
    decisao TEXT NOT NULL CHECK (decisao IN ('aprovar', 'rejeitar', 'corrigir')),
    correcao TEXT,                        -- se "corrigir", qual foi a correção?
    justificativa TEXT,                   -- motivo da decisão
    auditado_por TEXT NOT NULL CHECK (auditado_por IN ('llm', 'humano', 'admin', 'sistema')),
    ip_auditoria TEXT,                    -- IP de quem fez auditoria
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_auditoria_candidato_id ON falai_doutor_normalizacao.auditoria(candidato_id);
CREATE INDEX IF NOT EXISTS idx_auditoria_decisao ON falai_doutor_normalizacao.auditoria(decisao);
CREATE INDEX IF NOT EXISTS idx_auditoria_auditado_por ON falai_doutor_normalizacao.auditoria(auditado_por);
CREATE INDEX IF NOT EXISTS idx_auditoria_criado_em ON falai_doutor_normalizacao.auditoria(criado_em);


-- ================================================================
-- TRIGGERS (opcional)
-- ================================================================
-- Auto-atualizar timestamps

CREATE OR REPLACE FUNCTION falai_doutor_normalizacao.update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.atualizado_em = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_categorias_sintomas_timestamp ON falai_doutor_normalizacao.categorias_sintomas;

CREATE TRIGGER trigger_categorias_sintomas_timestamp
BEFORE UPDATE ON falai_doutor_normalizacao.categorias_sintomas
FOR EACH ROW
EXECUTE FUNCTION falai_doutor_normalizacao.update_timestamp();

DROP TRIGGER IF EXISTS trigger_sintomas_timestamp ON falai_doutor_normalizacao.sintomas;

CREATE TRIGGER trigger_sintomas_timestamp
BEFORE UPDATE ON falai_doutor_normalizacao.sintomas
FOR EACH ROW
EXECUTE FUNCTION falai_doutor_normalizacao.update_timestamp();

DROP TRIGGER IF EXISTS trigger_sinonimos_timestamp ON falai_doutor_normalizacao.sinonimos;

CREATE TRIGGER trigger_sinonimos_timestamp
BEFORE UPDATE ON falai_doutor_normalizacao.sinonimos
FOR EACH ROW
EXECUTE FUNCTION falai_doutor_normalizacao.update_timestamp();


-- ================================================================
-- VIEWS (opcional)
-- ================================================================
-- Vista para facilitar queries comuns

CREATE OR REPLACE VIEW falai_doutor_normalizacao.vw_sinonimos_normalizacao AS
SELECT 
    s.id as sinonimo_id,
    s.termo as termo_sinonimo,
    s.sintoma_id,
    sin.termo as termo_canonico,
    cat.codigo as categoria,
    s.status,
    s.origem,
    s.criado_em
FROM falai_doutor_normalizacao.sinonimos s
JOIN falai_doutor_normalizacao.sintomas sin ON s.sintoma_id = sin.id
LEFT JOIN falai_doutor_normalizacao.categorias_sintomas cat ON sin.categoria_id = cat.id
WHERE sin.ativo = TRUE AND s.status = 'aprovado';


CREATE OR REPLACE VIEW falai_doutor_normalizacao.vw_base_candidata_pendentes AS
SELECT 
    bc.id,
    bc.input_original,
    bc.normalizado_sugerido,
    bc.score_e5,
    bc.score_ollama_confianca,
    bc.origem,
    COUNT(a.id) as auditoria_count
FROM falai_doutor_normalizacao.base_candidata bc
LEFT JOIN falai_doutor_normalizacao.auditoria a ON bc.id = a.candidato_id
WHERE bc.status = 'pendente'
GROUP BY bc.id
ORDER BY bc.criado_em DESC;


-- ================================================================
-- COMENTÁRIOS
-- ================================================================
-- Documentar estrutura

COMMENT ON TABLE falai_doutor_normalizacao.sintomas IS 'Termos médicos canônicos que serão indexados no Qdrant com embeddings E5';
COMMENT ON TABLE falai_doutor_normalizacao.sinonimos IS 'Variações de termos (como usuários falam) que apontam a sintomas canônicos';
COMMENT ON TABLE falai_doutor_normalizacao.base_candidata IS 'Candidatos aguardando auditoria para melhoria contínua do vocabulário';
COMMENT ON TABLE falai_doutor_normalizacao.auditoria IS 'Rastreamento completo de aprovações/rejeições de normalizações';


-- ================================================================
-- PERMISSÕES (opcional - se usar usuários diferentes)
-- ================================================================
-- GRANT SELECT ON ALL TABLES IN SCHEMA falai_doutor_normalizacao TO api_user;
-- GRANT INSERT, UPDATE, DELETE ON falai_doutor_normalizacao.sintomas, falai_doutor_normalizacao.sinonimos TO api_user;
-- GRANT INSERT ON falai_doutor_normalizacao.inputs, falai_doutor_normalizacao.outputs, falai_doutor_normalizacao.base_candidata, falai_doutor_normalizacao.auditoria TO api_user;


COMMIT;
